### ISSUE TITLE
ng-valid when form control is invalid

### ISSUE THREAD

**Issue by fernandomeridamatilla** [juanjotorres90/ngx-material-intl-tel-input#11]
Using angular 18 and the latest version of this library, it happens that the formControl associated to the ngx-material-intl-tel-input component is invalid, but the ng-valid class is shown.

![Captura de pantalla 2024-07-25 a las 14 41 03](https://github.com/user-attachments/assets/646641c1-3edb-4852-aa86-8448e317b3a4)
![Captura de pantalla 2024-07-25 a las 14 41 08](https://github.com/user-attachments/assets/d214f3ea-fd49-4a4c-bde0-19b638f42a94)
![Captura de pantalla 2024-07-25 a las 14 42 47](https://github.com/user-attachments/assets/a28c2cdd-b080-49f9-8424-c65b03f95b0f)

**Comment by juanjotorres90** [comment]
It should be fixed in the latest release(18.1.1). Let me know if it works.

Saludos!

**Comment by fernandomeridamatilla** [comment]
Mañana pruebo, tengo instalada la 18.1.0, instalo la nueva y te digo si me ha funcionado. !Muchas gracias!

**Comment by fernandomeridamatilla** [comment]
I have just to update the library and works fine, thanks a lot!!
