### ISSUE TITLE
Search bar comes behind the modal

### ISSUE THREAD

**Issue by nouaim** [juanjotorres90/ngx-material-intl-tel-input#18]
I am using a modal from primeng and failed to have the search bar appear the normal way, while there is no problem with other pages. Do you have an idea to fix this?

![Screenshot from 2024-09-03 16-09-51](https://github.com/user-attachments/assets/271476bb-adb6-4098-9960-ba101ac83cda)
![Screenshot from 2024-09-03 16-10-05](https://github.com/user-attachments/assets/fbc2833d-b800-47e0-b443-a804da92d326)

**Comment by juanjotorres90** [comment]
Hi,

It seems that there's a problem with the 'z-index' CSS property and both overlays (the Angular Material and PrimeNG modal ones).

Try adding to your global styles this:

```css
.cdk-overlay-container {
  z-index: 1101;
}
```
<img width="647" alt="Captura de pantalla 2024-09-04 a las 17 31 46" src="https://github.com/user-attachments/assets/29e3db35-62ea-4374-ab2f-198d865d5705">

**Comment by nouaim** [comment]
it works well. thanks a lot. I really appreciate your help!
