### ISSUE TITLE
Create style variables to customize component

### ISSUE THREAD

**Issue by tluzvid22** [juanjotorres90/ngx-material-intl-tel-input#21]
Create style variables to allow developers to modify key styles such as colors, fonts, spacing, and other design elements. These variables should provide an easy way to customize the component’s look without altering its core structure.

Examples: 
![image](https://github.com/user-attachments/assets/bc447d4d-f406-45b1-a693-3cb52758ab51)
![image](https://github.com/user-attachments/assets/8b0e9b13-8050-4613-8471-22e441bd3a45)

**Comment by CalvinMunava** [comment]
any updates on this ?

im struggling to customize the styling

**Comment by juanjotorres90** [comment]
Check this: https://github.com/juanjotorres90/ngx-material-intl-tel-input/issues/19#issuecomment-2332390908

This library uses Angular Material components, so styling them should be similar.

This is an open-source project, feel free to request a PR to add any variables you might need.

Thank you 😉
