### ISSUE TITLE
No provider for _MatSelect!

### ISSUE THREAD

**Issue by grigoryanmartin20** [juanjotorres90/ngx-material-intl-tel-input#27]
I've followed the documentation, and when I added the component, this error appeared. (Angular 19)

![Screenshot 2024-12-02 150602](https://github.com/user-attachments/assets/2acea429-852d-4104-92ef-2a35ddedb8b4)

**Comment by rad3** [comment]
I had this problem when updating to Angular 19 too - as a work-around I installed and pinned "ngx-mat-select-search" to version "6.0.0"

**Comment by juanjotorres90** [comment]
If you are using Angular 19, version [19.0.0](https://github.com/juanjotorres90/ngx-material-intl-tel-input/releases/tag/19.0.0) with support for it has just been released.
