### ISSUE TITLE
Recommandation/Request (getCountryCode)

### ISSUE THREAD

**Issue by elephantcode225** [juanjotorres90/ngx-material-intl-tel-input#30]
Hello I really liked it. 
Can you add a function/ouput to get only the country code ?

**Comment by juanjotorres90** [comment]
Hi!
Thank you for your interest in improving this library.

I guess you would like an output emitter similar to "currentValue" but only for the country code (e.g.: '+225') right?

<img width="300" alt="Captura de pantalla 2024-12-11 a las 19 07 38" src="https://github.com/user-attachments/assets/3022cdc5-d5ff-4130-b303-35634a0e2c60" />

**Comment by ibraweb** [comment]
Hello,

I really appreciate your work. Currently, I can only retrieve the phone number from currentValue. Would it be possible to add the retrieval of the CountryISO as well? For example, for France: fr.

Thank you in advance for your help!

**Comment by ibraweb** [comment]
Hello I really liked it. Can you add a function/ouput to get only the country code ?

With a regex, you can easily retrieve the first 4 characters returned by currentValue.

**Comment by juanjotorres90** [comment]
Version [19.1.0](https://github.com/juanjotorres90/ngx-material-intl-tel-input/releases/tag/19.1.0) has just been released. 🎉
