### ISSUE TITLE
get country ISO

### ISSUE THREAD

**Issue by ibraweb** [juanjotorres90/ngx-material-intl-tel-input#31]
Hi,
I really appreciate your work. Currently, I can only retrieve the phone number from currentValue. Would it be possible to add the retrieval of the CountryISO as well? For example, for France: fr.

Thank you!

**Comment by juanjotorres90** [comment]
Hi,

Sure! It will be implemented soon in the next release.

Expect something like this: (currentCountryISO)

Thank you for your support!

**Comment by ibraweb** [comment]
Great thanks

**Comment by juanjotorres90** [comment]
Version [19.1.0](https://github.com/juanjotorres90/ngx-material-intl-tel-input/releases/tag/19.1.0) has just been released. 🎉
