### ISSUE TITLE
NgxMaterialIntlTelInputComponent

### ISSUE THREAD

**Issue by abhinaykm** [juanjotorres90/ngx-material-intl-tel-input#6]
<ngx-material-intl-tel-input  ></ngx-material-intl-tel-input>
 
 how to use formControlName so that we can get value of phone no
 
  this.addOrgGroupForm = this.fb.group({
      id: [0],
      email: ['', [Validators.required]],
      phone: new FormControl(''),     
    });
  
    submitForm() {
      console.log(this.addOrgGroupForm.value);
     }
     <form class="register-form m-4" [formGroup]="addOrgGroupForm" (ngSubmit)="submitForm()">
      <div class="row"> 
              <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-2">
                <mat-form-field class="example-full-width mb-3" appearance="outline">
                  <mat-label> Name</mat-label>
                  <input matInput formControlName="name" required>
                  @if (addOrgGroupForm.get('name')?.hasError('required')|| addOrgGroupForm.get('name')?.touched) {
                    <mat-error >
                      {{displayErrMessage.required}}
                    </mat-error>
                    }
                </mat-form-field>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-2">
               <ngx-material-intl-tel-input   > </ngx-material-intl-tel-input>
                      </div>
      </div>
     </form>

**Comment by juanjotorres90** [comment]
Hi,

You can pass your FormControl to the telephone input component.

Something like this should be ok:

<ngx-material-intl-tel-input [fieldControl]="addOrgGroupForm.get('phone')"></ngx-material-intl-tel-input>

Let me know if it works.

**Comment by abhinaykm** [comment]
import { NgxMaterialIntlTelInputComponent } from 'ngx-material-intl-tel-input';
@Component({
  selector: 'app-organisation-groups',
  standalone: true,
  imports: [
    FormsModule,
    ReactiveFormsModule,
    MaterialModule,
    NgxMaterialIntlTelInputComponent,
  ],
  export class OrganisationGroupsComponent extends UnsubscribeOnDestroyAdapter implements OnInit {
  ngOnInit(): void {
this.initForm() 
}
 initForm() {
    this.addOrgGroupForm = this.fb.group({
      id: [0],
      name: ['', [Validators.required]],
      email: ['', [Validators.required]],
      phone: new FormControl(''),
    });
  }
  <form class="register-form m-4" [formGroup]="addOrgGroupForm" (ngSubmit)="submitForm()">
   <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-2">
                <mat-form-field class="example-full-width mb-3" appearance="outline">
                  <mat-label> Name</mat-label>
                  <input matInput formControlName="name" required>
                  @if (addOrgGroupForm.get('name')?.hasError('required')|| addOrgGroupForm.get('name')?.touched) {
                    <mat-error >
                      {{displayErrMessage.required}}
                    </mat-error>
                    }
                </mat-form-field>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-2">
                    <mat-form-field class="example-full-width mb-3" appearance="outline">
                      <mat-label>Email</mat-label>
                      <input matInput formControlName="email" required>
                      @if (addOrgGroupForm.get('email')?.hasError('required')|| addOrgGroupForm.get('email')?.touched) {
                        <mat-error >
                          {{displayErrMessage.required}}
                        </mat-error>
                        }
                    </mat-form-field>
                    </div>
                     <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-2">
                      <ngx-material-intl-tel-input   
                      [fieldControl]="addOrgGroupForm.get('phone')!">
                      </ngx-material-intl-tel-input>
                   </div>
                   
                   when i am using filedControl getting error .
                   Type 'AbstractControl<any, any>' is missing the following properties from type 'FormControl<string | null>': defaultValue, registerOnChange, registerOnDisabledChange

can you provide me code how to use formControlName or something else so that i can print data of phone on submit 
submitForm() {
console.log(this.addOrgGroupForm.value);
}

**Comment by juanjotorres90** [comment]
This is working for me:

`addOrgGroupForm: FormGroup = this.fb.group({
    id: [0],
    description: ['', [Validators.required]],
    name: ['', [Validators.required]],
    email: ['', [Validators.required]],
    phone: [''],
  });`

`get phoneControl(): FormControl {
    return this.addOrgGroupForm.get('phone') as FormControl;
  }`

If the input is required and you need to set an initial value your HTML should look like this:

`<ngx-material-intl-tel-input
    [fieldControl]="phoneControl"
    [initialValue]="'+91 80900 00120'"
    [required]="true"
  >
  </ngx-material-intl-tel-input>`

**Comment by abhinaykm** [comment]
Hi, 
how can textlabel remove 
<ngx-material-intl-tel-input
    [fieldControl]="phoneControl"
    [initialValue]="'+91 80900 00120'"
    [required]="true"
  >

  </ngx-material-intl-tel-input>

**Comment by juanjotorres90** [comment]
Just replace textLabels by empty strings:

```
<ngx-material-intl-tel-input
    [fieldControl]="phoneControl"
    [initialValue]="'+91 80900 00120'"
    [required]="true"
    [textLabels]="textLabels"
  >
  </ngx-material-intl-tel-input>
```

```
textLabels = {
      mainLabel: '',
      codePlaceholder: '',
      searchPlaceholderLabel: '',
      noEntriesFoundLabel: '',
      nationalNumberLabel: '',
      hintLabel: '',
      invalidNumberError: '',
      requiredError: ''
    };
```

**Comment by juanjotorres90** [comment]
In the latest release(18.0.1) you can use fieldControlName to pass the phone formControlName from your form group.
