### ISSUE TITLE
HI can we remove phone icon 

### ISSUE THREAD

**Issue by abhinaykm** [juanjotorres90/ngx-material-intl-tel-input#9]
HI can we remove phone icon 
  <ngx-material-intl-tel-input
          [preferredCountries]="['in', 'us', 'nz']"
          [enablePlaceholder]="true"
          [enableSearch]="true"
          cssClass="country-selector"
          (countryChanged)="changeCountry($event)"
          [fieldControl]="phoneControl"
          [initialValue]="''"
          [textLabels]="textLabels"
          >
        </ngx-material-intl-tel-input>

**Comment by juanjotorres90** [comment]
I will add an option to remove the phone icon in a future release.

For now you can use css just to hide it:

`
    ngx-material-intl-tel-input::ng-deep {
      mat-icon {
        display: none;
      }
    }
`

**Comment by juanjotorres90** [comment]
In the latest release(18.1.0) you can hide the phone icon with the option 'hidePhoneIcon'.
